# Generated by Django 6.0.5 on 2026-07-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('feed_like', 'Feed like'), ('feed_comment', 'Feed comment'), ('track', 'Track'), ('scholarship', 'Scholarship'), ('system', 'System')], max_length=20),
        ),
    ]
